### ISSUE TITLE
Complain: Please stop blaming open source components before blaming closed source components

### ISSUE THREAD

**Issue by xry111** [glfs-book/glfs#14]
When something (no matter open-source or closed-source) crashes, we should first analysis if it's a bug in the program itself, before blaming its dependencies.  Even if the crash seems a SIGSEGV in a library, it does not mean the library is buggy.  For example, if something (no matter open-sourced or closed-sourced) calls `strlen` with a `NULL` pointer, we'll see a SIGSEGV in `strlen` but it obviously does not mean `strlen` is buggy.

This should be obvious.  But when the library is open-source but the program is closed-source, people often do things in a wrong way.  Instead they poke with the library in some questionable way to make the program seem to work, and blame the open source developers for questioning or rejecting their pokes.

Yes poking and blaming the source code may seem easier than poking or blaming the binary, but doing so is just unfair, in both technical and economical aspects.

Technically, they hide their source code so they disallow us to figure out the issue on our own.  Thus they should have provided a better customer support to compensate, instead of stressing all the customer pressure to us.

Economically, we get nothing from developing LFS, GCC, Glibc, and etc. but they earn a lot of money selling their graphic cards, games, and etc.

This is just a complain so you can just close it w/o any action.  But if you have some "troubleshooting" page please consider document the info (maybe removing or rephrasing the over-aggressive sentences).

**Comment by zeckma-tech** [comment]
I'm sorry if some sentences in GLFS are harsh and paint open source projects in a bad light. However, while I do see something I forgot to clean up in the Steam Troubleshooting page, I personally don't see what sentences could be part of the issue you're describing.

If you can, it would be appreciated if you'd point them out for me so I can fix them. Thanks!

**Comment by xry111** [comment]
Closing as this was written in a bad mood.  I'll make a PR myself if I can find a suitable location in the book for a tuned-down version.

**Comment by zeckma-tech** [comment]
This sounds good. Thanks in advance!
