### ISSUE TITLE
x11perf upstream moved

### ISSUE THREAD

**Issue by tox-wtf** [glfs-book/glfs#16]
Hello, x11perf's upstream has changed, and it's out of date in GLFS and BLFS. I'm opening this as an issue since app-7-list no longer works for downloading x11perf because it's now stored at https://www.x.org/archive/individual/test instead of /app. As such, fixing this would likely require changes to the Xorg Applications page. I don't know how you'd like to tackle those changes, so I'll leave that to you.

The latest version of x11perf is 1.7.0.

**Comment by zeckma-tech** [comment]
Removed it in https://github.com/glfs-book/glfs/commit/c45499440c367842d03b1e9bfacdd106296f9511

Too much work over nothing so it's getting shaft.
