### ISSUE TITLE
Add "Available Parameters" section to each package

### ISSUE THREAD

**Issue by zeckma-tech** [glfs-book/glfs#2]
Originally https://github.com/Zeckmathederg/glfs/issues/19. This issue has been moved here as it will take a very, very long time to do. Therefore, any migrations that may happen would not happen for months to a year.

**Comment by zeckma-tech** [comment]
This issue may be reworked as it is too much work to implement it as it is now. A possible alternative is to detail what to check for possible options instead of laying all of them out. This is a much more simple solution.

**Comment by tox-wtf** [comment]
I agree that explaining how to check possible options is easier, more maintainable, (and probably better in the long run). I think explaining, for instance, `nvidia*.run -A` displays possible options, or `less meson_options.txt`, etc., would be the best solution here.

**Comment by zeckma-tech** [comment]
> I agree that explaining how to check possible options is easier, more maintainable, (and probably better in the long run). I think explaining, for instance, `nvidia*.run -A` displays possible options, or `less meson_options.txt`, etc., would be the best solution here.

Will do this.
