### ISSUE TITLE
add proton for steam

### ISSUE THREAD

**Issue by zhw2101024** [glfs-book/glfs#26]
It is very useful for playing some games for windows, and is officially support by steam.

**Comment by tox-wtf** [comment]
What's the use-case for this? Steam's client natively supports Proton after changing a few settings. For any non-Steam games, you can just add them to Steam and force your desired version of Proton (which may or may not work depending on the game).

Are you trying to use Proton independently of Steam?

**Comment by zeckma-tech** [comment]
If you mean ProtonGE, I will not be adding instructions for it as it is pretty much distro agnostic. Like the *LFS books, GLFS doesn't really go out of its way to teach users how to use software in general. Steam is such an example. There are plenty of guides on how to get your Steam installation ready for optimal gaming and such. It's pretty easy to get set up, anyway.
