### ISSUE TITLE
Add a stable and nightly branch

### ISSUE THREAD

**Issue by tox-wtf** [glfs-book/glfs#28]
Adding a stable and nightly branch would provide readers with more options, and would improve stability. The nightly branch would also ease the addition of new packages/sections. It would allow readers who desire it access to the latest documentation and packages, and likewise for those who want more stable systems.

**Proposed behavior:**
- nightly: main branch on which changes are made
- trunk: 14 days behind nightly
- stable: 14 days behind trunk (28 days behind nightly)

The day delays are merely suggestions; feel free to change them according to your liking. This branch scheme could probably be implemented by working on nightly, copying commits >= 14 days old to trunk, >= 28 days old to stable, and be automated with GHA. (Though, note that I'm not familiar with GHA, and there may be superior ways of automating this.)

Thanks!

**Comment by zeckma-tech** [comment]
`trunk` is meant for development where all the new commits are pushed to. So it will stay as it is. A `nightly` branch doesn't make too much sense to me. Now stable is where it does sort of make sense. It would be useful if the book actually had releases planned out but it doesn't right now, so it would only be useful if someone obtains the source. It still causes problems as MLFS is rolling release only.

So until MLFS has stable releases, I also won't be making stable releases of GLFS, but I'm not throwing the idea of a stable branch out the window. It'd be for something down the road so I won't implement it right now. I will be keeping this issue open and will be thinking on it, though. Thanks for the suggestion!

**Comment by tox-wtf** [comment]
Gotcha. I was under the impression trunk served as the primary/default branch.

**Comment by zeckma-tech** [comment]
It is, it's also just where all the development happens. BLFS and LFS have a lot of branches, but basically everything happens on `trunk` as they would happen on `master` or `main` for other projects, then when we get ready for a stable release, I take it our changes merge into `stable`, then we play catch up with package versions

**Comment by zeckma-tech** [comment]
I have made a new [stable](https://github.com/glfs-book/glfs/tree/stable) branch which tracks `trunk`. How often it will be updated is unknown right now and the `stable` branch is useless right now for most. The good news is it is made now and it is up to date.
